/**
 * Common CSS styles for PDF reports
 */
export const reportStyles = `
    body { 
        font-family: Arial, sans-serif; 
        padding: 30px;
        color: #333;
    }
    h1 { 
        color: #60A5FA; 
        border-bottom: 3px solid #60A5FA;
        padding-bottom: 10px;
        margin-bottom: 20px;
    }
    h2 {
        color: #3B82F6;
        margin-top: 25px;
        margin-bottom: 15px;
    }
    .info-row {
        display: flex;
        justify-content: space-between;
        padding: 10px 0;
        border-bottom: 1px solid #E5E7EB;
    }
    .label {
        font-weight: bold;
        color: #6B7280;
    }
    .value {
        color: #111827;
        font-weight: 600;
    }
    .highlight {
        background-color: #EFF6FF;
        padding: 15px;
        border-radius: 8px;
        margin: 15px 0;
    }
    .savings {
        background-color: #D1FAE5;
        padding: 15px;
        border-radius: 8px;
        margin: 15px 0;
        border-left: 4px solid #10B981;
    }
    .summary-box {
        background-color: #EFF6FF;
        padding: 20px;
        border-radius: 8px;
        margin: 20px 0;
    }
    .summary-row {
        display: flex;
        justify-content: space-between;
        padding: 12px 0;
        border-bottom: 1px solid #BFDBFE;
    }
    .summary-label {
        font-weight: bold;
        color: #1E40AF;
    }
    .summary-value {
        color: #1E3A8A;
        font-weight: 600;
        font-size: 18px;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 15px;
    }
    th {
        background-color: #60A5FA;
        color: white;
        padding: 12px;
        text-align: left;
    }
    td {
        padding: 10px;
        border-bottom: 1px solid #E5E7EB;
    }
    tr:nth-child(even) {
        background-color: #F9FAFB;
    }
    .footer {
        margin-top: 30px;
        padding-top: 20px;
        border-top: 2px solid #E5E7EB;
        color: #6B7280;
        font-size: 12px;
        text-align: center;
    }
`;

/**
 * Generate footer HTML for reports
 */
export function generateReportFooter(): string {
    return `
        <div class="footer">
            <p>Generated by Loan Copilot on ${new Date().toLocaleDateString()}</p>
            <p>⚠️ This is for informational purposes only. Please verify all calculations with your lender.</p>
        </div>
    `;
}

/**
 * Wrap HTML content in a complete HTML document with styles
 */
export function wrapInHtmlDocument(title: string, bodyContent: string): string {
    return `
        <html>
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <style>${reportStyles}</style>
            </head>
            <body>
                <h1>${title}</h1>
                ${bodyContent}
                ${generateReportFooter()}
            </body>
        </html>
    `;
}

/**
 * Format period (months) as readable text
 * @param months Number of months
 * @returns Formatted string like "2 years 3 months" or "15 months"
 */
export function formatPeriod(months: number): string {
    if (months >= 12) {
        const years = Math.floor(months / 12);
        const remainingMonths = months % 12;
        const yearText = `${years} year${years !== 1 ? 's' : ''}`;
        const monthText = remainingMonths > 0 ? ` ${remainingMonths} month${remainingMonths !== 1 ? 's' : ''}` : '';
        return yearText + monthText;
    }
    return `${months} month${months !== 1 ? 's' : ''}`;
}
